
export const sillyTodos = [
    "Find Atlantis",
    "Race a turtle",
    "Hug a tree",
    "Try to fly",
    "Take over the world",
    "Win a staring contest",
    "Get abducted by aliens",
    "Invent a new color",
    "Be a superhero for a day",
    "Make a time machine",
    "Write a novel in a day",
    "Have a water balloon fight",
    "Sleep under the stars",
    "Talk to animals",
    "Build a sandworm",
    "Live in a treehouse",
    "Get superpowers",
    "Build a robot army",
    "Travel to Mars",
    "Ride a unicorn",
    "Teach a cat to fetch",
    "Learn to beatbox",
    "Write a poem about pizza",
    "Make a smoothie",
    "Try a new workout",
    "Create a vision board",
    "Do a silly dance",
    "Learn a new language",
    "Take a bubble bath",
    "Watch a stand-up comedy show",
    "Make a craft",
    "Try a new type of tea",
    "Take a selfie with a stranger",
    "Write a joke",
    "Go for a bike ride",
    "Learn to knit",
    "Organize your closet",
    "Try a new fashion trend",
    "Watch a TED talk",
    "Take a yoga class",
    "Make a TikTok video",
    "Learn to whistle",
    "Solve a Rubik's Cube",
    "Build a fort",
    "Write a short story",
    "Go for a hike",
    "Take a nap",
    "Learn a magic trick",
    "Plant a garden",
    "Try a new recipe",
    "Teach a goldfish to play basketball",
    "Learn to yodel",
    "Write a haiku about JavaScript",
    "Make a cake from scratch",
    "Invent a new word and use it all day",
    "Try a new hair color",
    "Create a meme",
    "Practice juggling",
    "Build a sandcastle",
    "See how many push-ups you can do",
    "Make a paper airplane",
    "Learn to moonwalk",
    "Do a puzzle",
    "Play a practical joke",
    "Watch a classic movie",
    "Sing in the shower",
    "Go stargazing",
    "Visit a museum",
    "Write a letter to your future self",
    "Try a new hobby",
    "Teach a parrot to say 'Help, I've been turned into a parrot!'",
    "Learn to speak whale",
    "Convince someone that HTML is a programming language",
    "Get lost in a new city on purpose",
    "Find a way to make coffee without a coffee maker",
    "Create a new dance move and name it after yourself",
    "Write a love letter to your favorite programming language",
    "Have a conversation with Siri or Alexa and see where it goes",
    "Try a food you've never had before",
    "See how long you can hold a plank for (and then brag about it to your friends)",
];

// function to return a random item from the sillyTodos array
export const randomSillyTodo = () => {
    return sillyTodos[Math.floor(Math.random() * sillyTodos.length)]
}